# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Growlibb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Growlibb

  # RxSwift & Cocoa
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  # RxDataSource
  pod 'RxDataSources', '~> 5.0'
  # RxGesture
  pod 'RxGesture'
  # RxKeyboard
  pod 'RxKeyboard'
  # Moya with rx
  pod 'Moya/RxSwift', '~> 15.0'
  # SwiftyJson
  pod 'SwiftyJSON', '~> 4.0'

  # SnapKit
  pod 'SnapKit', '~> 5.0.0'
  # Then
  pod 'Then'
  # Alamofire
  pod 'Alamofire', '~> 5.4.4'
  # SwiftKeychainWrapper
  pod 'SwiftKeychainWrapper'
  # SwiftGen
  pod 'SwiftGen', '~> 6.0'

  # Firebase
  pod 'Firebase/Analytics'
  # Firebase 이메일  
  pod 'Firebase/Auth'
  # Firebase 푸시알림
  pod 'Firebase/Messaging'
  # Firebase Crashlytics
  pod 'Firebase/Crashlytics'

  # Toast
  pod 'Toast-Swift', '~> 5.0.1'

  # Kingfisher
  pod 'Kingfisher', '~> 7.0'

  # Dropdown
  pod 'DropDown', '2.3.13'

  # Alamofire Logger
  pod 'AlamofireNetworkActivityLogger', '~> 3.4.0'

  # FSCalendar
  pod 'FSCalendar'

  # AnyFormatKit
  pod 'AnyFormatKit'

  # Gifu
  pod 'Gifu'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end

end
